const Lang = {
    ID: {
        startCooking: "Mulai Memasak",
        joinCommunity: "Ayo bergabung dengan komunitas kamu untuk memasak lebih baik!",
        getStarted: "Mulai",
        wellcomeBack: "Selamat Datang Kembali!",
        enterAccount: "Masukkan akun kamu disini",
        email: "Email",
        password: "Kata Sandi",
        forgotPassword: "Lupa kata sandi?",
        login: "Masuk",
        orContinueWith: "Atau lanjutkan dengan",
        dontHaveAccount: "Belum punya akun?",
        signup: "Daftar",
        required: "Harus diisi",
        wellcome: "Selamat datang!",
        haveAnAccount: "Sudah punya akun?",
        invalidEmail: "Email tidak valid",
        min8: "Minimal 8 karakter",
        includeUppercase: "Mengandung huruf besar",
        includeLowercase: "Mengandung huruf kecil",
        includeNumber: "Mengandung numor",
        includeSymbol: "Mengamdung simbol",
        passwordMustContain: "Kata sandi kamu harus mengandung:",
        checkYourEmail: "Cek email kamu",
        weSendOTP: "Kami telah mengirim OTP ke email kamu",
        codeExpire: "Kode berakhir dalam:",
        verify: "Verifikasi",
        resend: "Kirim ulang",
        passwordRecovery: "Reset kata sandi",
        enterEmailForRecovery: "Masukkan email untuk reset kata sandi",
        sendOtp: "Kirim OTP",
        resetYourPassword: "Reset kata sandi",
        enterYourPassword: "Masukkan kata sandi",
        reset: "Reset",
        search: "Cari",
        category: "Kategory",
        all: "Semua",
        food: "Makanan",
        drink: "Minuman",
        searchSuggestions: "Rekomendasi Pencarian"
    },
    EN: {
        startCooking: "Start Cooking",
        joinCommunity: "Let's join our community to cook better food!",
        getStarted: "Get Started",
        wellcomeBack: "Wellcome Back!",
        enterAccount: "Please enter your account here",
        email: "Email",
        password: "Password",
        forgotPassword: "Forgot password?",
        login: "Login",
        orContinueWith: "Or continue with",
        dontHaveAccount: "Don't have account?",
        signup: "Sign Up",
        required: "This field is required",
        wellcome: "Wellcome!",
        haveAnAccount: "Have an account?",
        invalidEmail: "Invalid email",
        min8: "Atleast 8 characters",
        includeUppercase: "Contains uppercase",
        includeLowercase: "Contains lowercase",
        includeNumber: "Contains number",
        includeSymbol: "Contains symbol",
        passwordMustContain: "Your password must contain:",
        checkYourEmail: "Check your email",
        weSendOTP: "We have send OTP to your email",
        codeExpire: "Code expires in:",
        verify: "Verify",
        resend: "Send again",
        passwordRecovery: "Password recovery",
        enterEmailForRecovery: "Enter your email to recover your password",
        sendOtp: "Send OTP",
        resetYourPassword: "Reset your password",
        enterYourPassword: "Please enter your password",
        reset: "Reset",
        search: "Search",
        category: "Category",
        all: "All",
        food: "Food",
        drink: "Drink",
        searchSuggestions: "Search Sugeestions"
    }
}

export default Lang;